import "./globals.css";
import type { Metadata } from "next";
import { Jost } from "next/font/google";

// components
import ImageBtnLink from "./Components/buttons/ImageLink";
import IconLink from "./Components/buttons/IconLink";
import Btn from "./Components/buttons/Btn";
import Search from "./Components/inputs/Search";
import BtnGroup from "./Components/buttons/BtnGroup";

// images
import VotingImg from "../public/img/voting.png";
import BreedsImg from "../public/img/breeds.png";
import GalleryImg from "../public/img-links/gallery.png";
import SearchSvg from "./Components/icons/SearchSvg20";
import LikeSvg from "./Components/icons/LikeSvg30";
import DislikeSvg from "./Components/icons/DislikeSvg30";
import FavSvg from "./Components/icons/FavSvg20";
import FavColorSvg from "./Components/icons/FavFullSvg20";
import FavSvg30 from "./Components/icons/FavSvg30";
import FavFullSvg30 from "./Components/icons/FavFullSvg30";
import GalleryItem from "./Components/GalleryItem";
import CatPic from "../public/catpic.jpg"
import Select from "./Components/inputs/Select";
import UpdateSvg20 from "./Components/icons/UpdateSvg20";
import SortSvg20 from "./Components/icons/SortSvg20";
import UploadSvg20 from "./Components/icons/UploadSvg20";
import { BtnEnum } from "./Components/ComponentTypes";


const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <ImageBtnLink
          href="/"
          name="Voting"
          image={{ src: VotingImg, alt: "Clipboard", width: 100 }}
        />
        <ImageBtnLink
          href="/"
          name="Breeds"
          image={{ src: BreedsImg, alt: "Cat", width: 100 }}
        />
        <IconLink href="/" icon={{ Icon: SearchSvg }} />
        <Search placeHolder="Search for breeds by name" />
        <BtnGroup
          buttons={[
            { icon: { Icon: LikeSvg }, label: "Like" },
            { icon: { Icon: FavSvg30, IconActive: FavFullSvg30 }, label: "Favourite" },
            { icon: { Icon: DislikeSvg }, label: "Dislike" }
          ]}
        />
        <Select name="Order" options={["String1", "String2"]} width={300} />
        <Select name="Order" options={["String1", "String2"]} width={300}>
          <Btn icon={{ Icon: UpdateSvg20 }} />
        </Select>
        <Btn icon={{ Icon: SortSvg20 }} />
        <Btn icon={{ Icon: UploadSvg20 }} text=" Upload" type={BtnEnum.ACTIVABLE} />
        {children}
      </body>
    </html>
  );
}
