import "./globals.css";
import type { Metadata } from "next";
import { Jost } from "next/font/google";

// components
import ImageBtnLink from "./Components/ImageBtnLink";
import IconLink from "./Components/IconLink";
import IconBtn from "./Components/IconBtn";
import Search from "./Components/Search";
import BtnGroup from "./Components/BtnGroup";

// images
import VotingImg from "../public/img-links/voting.png";
import BreedsImg from "../public/img-links/breeds.png";
import GalleryImg from "../public/img-links/gallery.png";
import SearchSvg from "./Components/icons/SearchSvg20";
import LikeSvg from "./Components/icons/LikeSvg30";
import DislikeSvg from "./Components/icons/DislikeSvg30";
import FavSvg from "./Components/icons/FavSvg20";
import FavColorSvg from "./Components/icons/FavFullSvg20";
import FavSvg30 from "./Components/icons/FavSvg30";
import FavFullSvg30 from "./Components/icons/FavFullSvg30";
import GalleryItem from "./Components/GalleryItem";
import CatPic from "../public/catpic.jpg"
import Select from "./Components/Select";


const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="en">
      <body className={jost.className}>
        {/* <ImageBtnLink
          href="/"
          name="Voting"
          image={{ src: VotingImg, alt: "Clipboard", width: 100 }}
        /> */}
        {/* <IconLink href="/" Icon={SearchSvg} /> */}
        {/* <IconBtn isHoverable Icon={SearchSvg} /> */}
        {/* <Search placeHolder="Search for breeds by name" /> */}
        {/* <BtnGroup
          buttons={[
            { Icon: LikeSvg, label: "Like" },
            { Icon: FavSvg30, IconActive: FavFullSvg30, label: "Favourite" },
            { Icon: DislikeSvg, label: "Dislike" }
          ]}
        /> */}
        {/* <GalleryItem image={{ src: CatPic, alt: "Clipboard" }} /> */}
        <Select name="Order" options={["String1", "String2"]} width={300} isFilter />
        {children}
      </body>
    </html>
  );
}
